name: Build WPF App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore NothingX/NothingX.csproj

    - name: Build
      run: dotnet build NothingX/NothingX.csproj -c Release --no-restore

    - name: Publish
      run: dotnet publish NothingX/NothingX.csproj -c Release -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true --self-contained true -r win-x64 -o ./publish

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Nothing X-Executable
        path: "./publish/Nothing X.exe"

    - name: Create GitHub Release
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: "latest"
        name: "Latest Build"
        files: "./publish/Nothing X.exe"
        prerelease: true
